<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ASUS" name="Command line test" tests="1" failures="1" timestamp="6 Apr 2016 13:50:58 GMT" time="0.049" errors="0">
  <testcase name="test" time="0.001" classname="tvs.proj.testng.AppTest">
    <failure type="org.testng.TestException" message="
Expected exception tvs.proj.testng.exceptions.InvalidOperationException but got org.testng.TestException: 
Method AppTest.test()[pri:0, instance:tvs.proj.testng.AppTest@2f686d1f] should have thrown an exception of class tvs.proj.testng.exceptions.InvalidOperationException">
      <![CDATA[org.testng.TestException: 
Method AppTest.test()[pri:0, instance:tvs.proj.testng.AppTest@2f686d1f] should have thrown an exception of class tvs.proj.testng.exceptions.InvalidOperationException
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Method AppTest.test()[pri:0, instance:tvs.proj.testng.AppTest@2f686d1f] should have thrown an exception of class tvs.proj.testng.exceptions.InvalidOperationException
	... 25 more
... Removed 25 stack frames]]>
    </failure>
  </testcase>
</testsuite>
