<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="tvs.proj.testng.AppTest" duration-ms="49" started-at="2016-04-06T14:50:58Z" finished-at="2016-04-06T14:50:58Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="49" started-at="2016-04-06T14:50:58Z" finished-at="2016-04-06T14:50:58Z">
      <class name="tvs.proj.testng.AppTest">
        <test-method status="PASS" signature="buildTest()[pri:0, instance:tvs.proj.testng.AppTest@2f686d1f]" name="buildTest" is-config="true" duration-ms="15" started-at="2016-04-06T14:50:58Z" finished-at="2016-04-06T14:50:58Z">
        </test-method>
        <test-method status="FAIL" signature="test()[pri:0, instance:tvs.proj.testng.AppTest@2f686d1f]" name="test" duration-ms="1" started-at="2016-04-06T14:50:58Z" finished-at="2016-04-06T14:50:58Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected exception tvs.proj.testng.exceptions.InvalidOperationException but got org.testng.TestException: 
Method AppTest.test()[pri:0, instance:tvs.proj.testng.AppTest@2f686d1f] should have thrown an exception of class tvs.proj.testng.exceptions.InvalidOperationException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Expected exception tvs.proj.testng.exceptions.InvalidOperationException but got org.testng.TestException: 
Method AppTest.test()[pri:0, instance:tvs.proj.testng.AppTest@2f686d1f] should have thrown an exception of class tvs.proj.testng.exceptions.InvalidOperationException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1459)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1222)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.testng.TestException: 
Method AppTest.test()[pri:0, instance:tvs.proj.testng.AppTest@2f686d1f] should have thrown an exception of class tvs.proj.testng.exceptions.InvalidOperationException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1485)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:740)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	... 25 more
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
